// multilang support (0 == 'ru', 1 == 'en'
let translations = [ 
                [
                    'Список покупок',
                    '<code><br>1 - составляйте списки покупок<br><br>2 - отмечайте покупки по списку<br><br>3 - сохраняйте избранные списки<br><br>4 - устанавливайте напоминания<br></code>',
                    'Перейти к покупкам',
                    'Помогите нам стать лучше',
                    'Вы можете помочь нам сделать приложение лучше, отправив свои сохраненные списки покупок. Полученная информация поможет нам сделать приложение удобнее для использования. Вся передаваемая вами информация деперсонализированна мы получим только ваши списки покупок, без привязки к вашим персональным данным.',
                    'Отправить',
                    'Не отправлять',
                    'Сервис для составления списка покупок',
                    'Закончить покупки',
                    'Напоминания',
                    'Редактировать список',
                    'Наименование',
                    'Кол-во',
                    'Сохранить список в напоминяниях',
                    'Купить по списку',
                    'Статистика',
                    'Отмена',
                    'Завершить',
                    'Текущий прогресс будет утерян',
                    'В список покупок',
                    'Добавить',
                    'Отмена',
                    'Удалить список',
                    'Удалить',
                    'Список также будет удалён из напоминаний',
                    'Сохранить список',
                    'Название',
                    'Сохранить',
                    'Добавить напоминане',
                    'Комментарий',
                    'Загрузить список',
                    'Загрузить',
                    'Текущий список покупок будет изменён',
                    'Основные показатели',
                    'Заполните все поля',
                    'Copyright © 2020 Andranik Sarkisyan',
                    'шт', 'кг', 'г', 'л', 'мл',
                    'Список покупок', 'Позиции', 'План', 'Факт', 'Комментарий отсутствует'
                ],
                [
                    'Shopping list',
                    '<code><br>1 - make shopping lists<br><br>2 - mark your purchases in list<br><br>3 - save your favorite lists<br><br>4 - set reminders<br></code>',
                    'Go to shopping',
                    'Help us become better',
                    'You can help us make the app better by submitting your saved shopping lists. The information received will help us make the application more convenient to use. All information you transmit is depersonalized, we will only receive your shopping lists, without being linked to your personal data.',
                    'Send',
                    'Do not send',
                    'Service for compiling a shopping list',
                    'Finish shopping',
                    'Notifications',
                    'Edit list',
                    'Name',
                    'Qty',
                    'Save list in notifications',
                    'Buy from the list',
                    'KPI',
                    'Cancel',
                    'Complete',
                    'Current progress will be lost',
                    'Add to shopping list',
                    'Add',
                    'Cancel',
                    'Delete list',
                    'Delete',
                    'List will also be removed from notifications',
                    'Save List',
                    'Name',
                    'Save',
                    'Add notification',
                    'Comment',
                    'Load list',
                    'Load',
                    'Current shopping list will be changed',
                    'Basic indicators',
                    'Please fill all fields',
                    'Copyright © 2020 Andranik Sarkisyan',
                    'pc.', 'kg', 'g', 'l', 'ml',
                    'Shopping list', 'Items', 'Planned', 'Purchased', 'No comments'
                ]
    ];

module.exports = {translations};